### ISSUE TITLE
Adopt Better Standards for Project Code Linting

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#104]
The README file and the Travis CI configuration does not always adhere to best practices for code formatting. This project should use Black to format all of the source code. Additionally, it should ensure that the linting tools check this formatting so that a build in Travis CI will fail if the code is not correctly formatted.

**Comment by ilikerustoo** [comment]
@aubreypc I have run black on all the files and this seems to cause pylint errors which I will look into. Otherwise I have manually fixed every pylint and flake8 issue in all the `.py` files in and outside the `tests` folder. I needed to do this to pass Travis when implementing linting tools and conversion to pipenv in the travis.yml file

**Comment by ilikerustoo** [comment]
I have fixed more `pylint` issues after the restructure that are waiting to be merged from my branch `bugfix/ fixing-bugs-in-develop`. I have add `black --check` to Travis too.

**Comment by Lancasterwu** [comment]
This issue has been resolved.
