### ISSUE TITLE
Add New Algorithms to Support Team Creation

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#107]
This tool should support more advanced algorithms for forming teams. For instance, it might be possible to use the alternating variable method (AVM), hill climbing (HC), or a genetic algorithm (GA) to create the teams. Once these algorithms are added, they should have test cases for them and clear documentation in the README.

**Comment by Alex-Yarkosky** [comment]
In order to implement the ability to add a way for conflicts to between students to factored into the algorithms, we would like to include an attribute in the database for each student that is their conflicts. @barrezuetai please let us know whether or not you are willing to include this data within the database you are working to create.
