### ISSUE TITLE
Perform User Research to Understand Needs of the Software

### ISSUE THREAD

**Issue by aubreypc** [GatorEducator/gatorgrouper#129]
In order to give direction to this project, we need to come up with answers to the following questions:

- Who are our users?
- What problems are we trying to solve for our users?
- What features would help to solve those problems?

I suggest that we reach out to Allegheny professors from different departments in order to learn more about how they approach group assignments. This way, we can begin to answer the second and third questions.

[This site](https://www.usability.gov/what-and-why/user-research.html) gives a general overview of user research techniques, and [suggests a flowchart](https://www.usability.gov/how-to-and-tools/resources/ucd-map.html) for the user-centered design process.

**Comment by ursowilliam** [comment]
I can reach out to some Professors I have done group projects with at Allegheny College in many different types of classes. I will try to gather information on different group work they have done in the past and what has been successful versus unsuccessful. Along with ways in which they believe assigning groups is the best, to help think of possible new features. Along with this I will let them know the current features of the gatorgrader and see what they think could be added to make the grouping method better.

**Comment by aubreypc** [comment]
Sounds good, @ursowilliam! Please keep me posted on what you are hearing in their replies. We'll be using this to draft up a document on user experience / usability standards -- feel free to join #interface in Slack if you want to be involved in that part of the process.

Others are welcome to help out with this as well if they like! If someone wants to make a template email or something that might make things go quicker

**Comment by aubreypc** [comment]
In doing this user research, it may help if we [phrase our findings in terms of user stories](https://www.mountaingoatsoftware.com/agile/user-stories) in order to integrate them into the product design process.

**Comment by ursowilliam** [comment]
Below is the drafted up template email. Let me know what you all think and what changes I should make! You just have to copy and past the think as I wrote it in word.

[Template Software Engineering Email.docx](https://github.com/GatorEducator/gatorgrouper/files/2841592/Template.Software.Engineering.Email.docx)

**Comment by aubreypc** [comment]
@ursowilliam That looks like a good start! If I can suggest a couple small changes:

- Phrasing the introduction in terms of their needs & how this project will make their lives easier may make getting a response more likely
- It might be good to keep the questions (especially 2) open-ended / less tied to the existing features
- Similarly, I would suggest adding another question along the lines of "Do you use group assignments in your class? Why or why not?" so that we can get feedback from those who choose not to as well

Thanks for drafting this!

**Comment by ElisiaW** [comment]
@ursowilliam Hi, thank you for this template! I made a few edits to what was written. The content that @aubreypc still needs to be added, however. Thanks!

[Template.Software.Engineering.Email.docx](https://github.com/GatorEducator/gatorgrouper/files/2841775/Template.Software.Engineering.Email.docx)

**Comment by ursowilliam** [comment]
Thanks for the suggestions! Attached I have updated the template to best incorporate those suggestions. Let me know what you all think!
[Updated Software Engineering Email Template.docx](https://github.com/GatorEducator/gatorgrouper/files/2842039/Updated.Software.Engineering.Email.Template.docx)

**Comment by aubreypc** [comment]
@ursowilliam @ElisiaW  Nice work, this updated template looks good to me! 

Does anyone else have any final suggestions before we start to send out the emails?

I'm wondering if we should also consider students' attitudes toward group work as a jumping off point for thinking about how students will interact with the tool and what kind of features can facilitate that. (Luckily that research is a little simpler to do, since everyone in our class falls into that demographic!)

**Comment by ElisiaW** [comment]
I just realized that the software project is actually spelled wrong haha, updated! Also added a few more minor edits as well.

**Comment by paladp** [comment]
Looks good! Couple of quick things:

- Should "make this program useful as possible" be "make this program as useful as possible" ?
- Should "Your answers along with the others we collected" be "Your answers along with the others we collect" to correct for tense?

**Comment by paladp** [comment]
Additionally, I think the feedback we get from the professors can really help guide the description that should be created  as per issue #114.

**Comment by chenc-allegheny** [comment]
I can answer those as an instructor in language department:
I am an instructor of Chinese with a class size under ten.
1. Yes. I usually pair them up to have conversational practice.
2. If it is homework, I would let them find their partners. If it is in-class activity, I will have them team up with neighboring students. In Chinese classes, the class size is relatively small, compare to that in cmpsc classes, so my class is easier to manage. 
3. In a language class, a successful group work does not depend on the end result, it depends on how much practice happened in the group, and how the group activity brings a sense of community among the students. The most successful grouping work usually happen in a class in which students are all willing to participate, less about how I group them.
4. I think that if you design an activity that would encourage the students to participate, maybe a competitive activity, a reward, you don't have to worry about group them as much.
-----------------------------------------------------------------------------------------------------
As you can see, my answer must be very different from Prof. Kapfhammer. In fact, I prefer not to group students using a computer program, because I need to use the class time to interact with my students in Chinese as much as possible. If I want to group them randomly, I would walk next to them personally and have them draw a straw and have conversations with them while doing it.

I notice that our questions are all open answer questions. I suggest that we add some quantifiable questions or yes/no questions, for example, their class size: 1-5? 5-10? 10-20............? How often do you have group work in the class? Once a week? once a month? Would you be interested in a program that will help you group students together and keep track of their works? Y/N

I can also send our questionnaire to my colleagues in other schools with a much bigger class size. Maybe the problem is the class size not the subject.

**Comment by aubreypc** [comment]
Thank you @paladp and @chenc-allegheny for your suggestions and feedback! Here is a new draft of the template with the questions moved into a Google Form and some more quantifiable questions included.

Does this look ready to send out? Hopefully if we send the emails this afternoon we will have some responses by Tuesday's lab session.

> Dear Professor (Enter the name of the Professor),
>
> My name is (enter name) and I am part of a team of students developing a program called GatorGrouper. This program will allow professors to quickly and easily divide students into groups without the hassle of self-grouping during class. In order to make it as useful as possible to professors, we wanted to reach out to you in order to learn what challenges you face when it comes to group assignments, and what factors you think make groups successful or unsuccessful. Would you mind answering a few questions in order to help us in the development of this program? 
>
>Our survey should only take a few minutes to complete, and you can answer as few or as many questions as you like. You can find it here: 
https://docs.google.com/forms/d/e/1FAIpQLSf01M6TVX-HchKnFUZUbQeNf9veWvAzbvRde8K1eZZ7Jy5KKg/viewform?usp=sf_link
>
>Thank you for taking the time and effort to help the spring Software Engineering class in our current program development. Your input on these questions will help us shape GatorGrouper into a program that will be most beneficial to a large amount people. Your answers, along with the others we collect, will help us to summarize the most important features when developing this program. Thank you again for your time and your input!
>
>Sincerely,
>
>The Allegheny College Software Engineering Team

**Comment by paladp** [comment]
Looks good to me! I think the additional questions are going to be very useful.

**Comment by gkapfham** [comment]
I think that the completion of this survey is a great idea. Many thanks to all of the individuals who participated in the discussion of this issue! Can you please keep us updated once you have results? We should try to use the results from this survey to make decisions about how we will implement features and what features we should implement. Overall, great! :smile:

**Comment by aubreypc** [comment]
Several professors have responded to our survey so far! [Here's a spreadsheet containing the responses](https://docs.google.com/spreadsheets/d/1Q9jI-ik-eF3n9k-rg53qvdX0YXR7pZjFhLH5f_Mxf0c/edit?usp=sharing). A good next step might be to use these responses in order to write [user stories](https://www.mountaingoatsoftware.com/agile/user-stories) --- I was thinking we could start collecting those in the product design column of the [gatorgrouper project board](https://github.com/orgs/GatorEducator/projects/1#card-17459948).

**Comment by Alex-Yarkosky** [comment]
@aubreypc should this issue be considered `Done` and closed? Or do you see progress taking place related to it?
