### ISSUE TITLE
Design A Database schema for web app implementation

### ISSUE THREAD

**Issue by barrezuetai** [GatorEducator/gatorgrouper#133]
We've talked about creating a Web App for Gator Grouper so that it's more accessible. We will design a database schema that will store the information needed to create groups and store that information for future you.

**Comment by aubreypc** [comment]
Thanks for opening this issue! We will likely need at least the following models:

- User 
  - could be a professor a student --- best to keep it general to avoid any potential issues with users who are both students and professors in different courses
- Course / Organization
- Assignment / Project
- Group

We will need to figure out the best way to incorporate the existing grouping algorithms. Should they be methods on the Group model / on the Assignment model which then intantiate a new Group? Or should they be in controllers/ rather than models/? We will also need to figure out the best way to store the data used to form groups -- should we just store a JSON / CSV string, or is there a better way?

**Comment by duarte2025** [comment]
Which database will be used?

**Comment by aubreypc** [comment]
@duarte2025 IMO, some kind of SQL would probably be best. I believe Django supports PostgreSQL, MySQL, and SQLite out of the box -- PostgreSQL or MySQL would probably be better to use when we eventually deploy the site, but SQLite would likely be more convenient while developing.
