### ISSUE TITLE
Failing Pytest after changing No File Found Exception Handling

### ISSUE THREAD

**Issue by huangs1** [GatorEducator/gatorgrouper#209]
# Description of the Issue
The original No File Found Exception Handling in the `read_students_file.py` does not actually catch the exception. It does not actually raise an error when the function isn't reading in a file. So, I attempted to do it using a try-except block (this is all in the `enhance/FileNotFoundException` branch). Everything works normally when I run the program but when I run `pytest` a lot of tests are failing.

## Steps to Reproduce Issue

Run `pipenv run python3 gatorgrouper/utils/gatorgrouper.py --students-file "students.csv"` to see that the program actually works.

Run `pipenv run pytest -x -s --cov-config pytest.cov --cov-report term-missing --cov` to see what test cases are failing.

### Assigned Developers
@huangs1 @Lancasterwu

**Comment by paladp** [comment]
Just tried this and all tests pass for me. I used:

` pipenv run python3 gatorgrouper/utils/gatorgrouper.py --students-file students.csv `

Instead of the command provided, since I believe we don't have to pass the name of the file in quotes. I ran the test command as given and had all tests pass. Perhaps there is a problem with your CSV file?

**Comment by Lancasterwu** [comment]
Hi @paladp, the problem was that the exception handling for no_input_csv file does not work, which means if you try to run the program without an input csv file, it does not return any error message. If you change the exception handling part to make it recognize IOError, or added a try except block, many test cases will fail. Where you trying to run the `enhance/FileNotFoundException` branch?

**Comment by huangs1** [comment]
> Just tried this and all tests pass for me. I used:
> 
> `pipenv run python3 gatorgrouper/utils/gatorgrouper.py --students-file students.csv`
> 
> Instead of the command provided, since I believe we don't have to pass the name of the file in quotes. I ran the test command as given and had all tests pass. Perhaps there is a problem with your CSV file?

The command you are running is just used to run the program itself--this does not run any of the test files. I was saying that when I run `pytest` there were tests, which were originally not failing, were failing.

**Comment by Michionlion** [comment]
The reason the tests fail is that they expect the `read_student_file` method to always succeed, even when a file does not exist. If you are always required to provide a `csv` file, then your tests must be changed to automatically create one (use a fixture, like tmpdir or tmpfile, with some initialization). They should ***not*** depend on an outside file -- all testing content should be contained within the source.

**Comment by Lancasterwu** [comment]
Hi @Michionlion ,all tests pass when there is no input csv file in the repository, so I don't think `pytest fixture` are required for all test cases except `test_read_student_file`. The problem is probably due to that the functions can not recognize importing csv inside the `try except` block, but it does not make sense because the program still runs correctly.

**Comment by Lancasterwu** [comment]
I have talked with @Michionlion, the problem here is because of the fact that all test cases besides `read_students_file` are using the error message returned by exception handling, which they should not because there are no input csv files.
