### ISSUE TITLE
Survey Submit Button

### ISSUE THREAD

**Issue by ElisiaW** [GatorEducator/gatorgrouper#242]
# Description of the Issue
Currently, the submit button located in the survey.html file does not actually send the data to a database and instead does nothing.

## Add Detailed Comment with More Information
In order to save the information that is being submitted, it needs to be stored in a database so that it can be accessed for grouping students. As of now, there is no database that has been created for the use of this button.

**Comment by aubreypc** [comment]
Hi @ElisiaW & @finneyj2, thanks for opening this issue and looking into the survey functionality!

I wanted to give you an update on the current progress in the feature/survey branch, and give some suggestions for how to implement this.

I have been working on a stripped-down version of the survey feature, where the survey just allows students to mark other students as preferred. My rationale was that a page where professors could design a custom survey would require JavaScript to dynamically add & remove form fields, and we don't have enough time to design a high quality system for that.

[Here is the view function](https://github.com/GatorEducator/gatorgrouper/blob/feature/survey/gatorgrouper/views.py#L68) for the `/course/<class_id>/survey` page. It handles two cases:
- HTTP GET request - display the survey in its initial state
- HTTP POST request - process the data which is received when the user submits the form
    - My plan was to use [Django formsets](https://docs.djangoproject.com/en/2.1/topics/forms/formsets/) to handle the data entry. Right now there's a basic `StudentCompatibilityForm` in `forms.py` which represents a checkbox for marking a single student as preferred.

As far as I can tell, here are the steps necessary in order to get this feature working:

- Writing a database model to handle a student preference
    - [This PR](https://github.com/GatorEducator/gatorgrouper/pull/199) from @barrezuetai's branch defines a model for conflicts which would be suitable -- we would probably just want to rename it
- Modifying the Students model to associate each student with a particular user account
    - We need this in order to verify that the logged in user is enrolled in the class as a student
- In the code for the POST request, create student preferences in the database for each checked form in the formset, and delete any existing student preferences which have been unchecked
- In the code for the GET request, use any existing preferences to set the initial state of the checkbox
