### ISSUE TITLE
Delete Google Forms Interaction and Use a Local CSV File

### ISSUE THREAD

**Issue by gkapfham** [GatorEducator/gatorgrouper#97]
The system currently provides a feature that supports interaction with Google Forms. While there is merit in this feature, my concern is that it adds complexity and it hard to test with an automated test suite. As such, I suggest that we remove the Google Forms integration and instead ask the user to specify a CSV file that contains the results from a Google Form. While this is extra work for the user, I judge that it would make it easier for us to deliver a production quality tool.

**Comment by leonardoz15** [comment]
Should the issue about utilizing a JSON input rather than CSV belong here or should that be its own issue? I figured both will require code changes but could be tackled at the same time.

**Comment by paladp** [comment]
I was able to remove the google sheets integration on my own fork and will be setting up a pull request on @quigley-c fork to implement the changes. In my implementation I found that in ``read_student_file.py``, we use ```value == "True"```, which during my testing caused logical errors because my CSV file had "TRUE" instead. I changed it to ```value.lower() == "true"``` in an effort to address any further problems related to capitalization. I was wondering if this change is necessary, or if we can/should expect all entries to be written as "True" and it was just a mistake on my part. Additionally, if we do end up doing a JSON API, this may not even be an issue. Either way let me know what you think.
